[package]
name = "lz-vk"
version = "0.1.0"
edition = "2024"
build = "build.rs"
authors = [
    "Nimesh Acharya <Radonoxius@protonmail.com>",
]
license = "MIT"
repository = "https://github.com/Radonoxius/lz-vk"
keywords = ["vulkan", "gpu", "compression", "decompression"]
description = "A generic memory decompressor for GPUs using Vulkan"
rust-version = "1.85"

[dependencies]
libc = "0.2.189"
ash = { version = "0.38.0", features = ["std", "linked", "debug"] }

[dev-dependencies]
test-utils = { path = "test-utils" }